### ISSUE TITLE
Free software sadness

### ISSUE THREAD

**Issue by tgy** [texworld/betterbib#267]
I contributed to this repo in the past. I can't even use it for free now.

Just wanted to say I'm really disappointed because you were a free software contributor I admired and respected. Just came back to a now proprietary & encoded codebase. Pretty surprised that this is now the spirit.

**Comment by nschloe** [comment]
I've worked in free software for a long time, and unfortunately I've found that donation-based dev model don't work. Everyone's using it, even commercial enterprises, without giving back. People contributing back, like you, were very rare. That's why I decided to try a subscription-based model after the rewrite. And, frankly, it's not that expensive.

**Comment by gjolleyrogers** [comment]
Long time lurker, first time poster.  It is sad but we all gotta eat. More power to you all and thanks.
